version: "3"
services:
  app:
    image: kraken-interview
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db

    volumes:
      - ./data:/data/
    # ports:

  db:
    image: postgres:14.1
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kraken

    volumes:
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:

    # volumes:
    #   data:
    #     external: true      
