version: "3"
services:
  app:
    image: kraken-interview
    build: .
    depends_on:
      - postgres
    # ports:

  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres

# volumes: